<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{d2148b4f-ffc5-48fc-a830-0599cebfe4fc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bOut AT %Q*: ARRAY[0..7] OF BOOL;
	pwm AT %Q*: UINT;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[pwm:=4000;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>